version: '3'
services:

  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: debelogin
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "3306:3306"
  
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"